apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: alfa
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
type: kubernetes.io/dockerconfigjson

#kubectl create secret generic myregistrykey --from-file=.dockerconfigjson=config.json --type=kubernetes.io/dockerconfigjson -n alfa


k create ns articles-versoview-ns-qa user-versoview-ns-qa versoview-ai-ns-qa

kubectl create secret generic regcred --from-file=.dockerconfigjson=config.json --type=kubernetes.io/dockerconfigjson -n articles-versoview-ns-qa

